#!/usr/bin/env bash
# himalaya skill — installer.
#
# 1. Verifies (and if needed, installs) the `himalaya` CLI.
# 2. Writes ~/.config/himalaya/config.toml using env-var references so the
#    password never lands in a second file on disk — only in .env.
# 3. Smoke-tests with `himalaya envelope list -p 1 -s 1`.
#
# Idempotent: re-running overwrites the config with the latest values
# from the env. Safe to run from `skill install` or `skill setup`.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# --- 1. ensure himalaya is on PATH ---------------------------------------
if ! command -v himalaya >/dev/null 2>&1; then
  echo "himalaya not found — attempting install…"
  if command -v brew >/dev/null 2>&1; then
    brew install himalaya
  elif command -v cargo >/dev/null 2>&1; then
    cargo install himalaya
  elif command -v apt-get >/dev/null 2>&1; then
    echo "himalaya is not in the default apt repos."
    echo "install from https://github.com/soywod/himalaya/releases and re-run:"
    echo "  skill setup himalaya"
    exit 2
  else
    echo "no supported package manager (brew / cargo / apt) found."
    echo "install himalaya manually: https://github.com/soywod/himalaya"
    exit 2
  fi
fi

HIM_VERSION="$(himalaya --version 2>/dev/null | head -1 || echo 'unknown')"
echo "✓ $HIM_VERSION"

# --- 2. load env from .env -----------------------------------------------
ENV_FILE="$ROOT/.env"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "ERROR: $ENV_FILE not found — run 'skill setup himalaya' first." >&2
  exit 3
fi

# Minimal dotenv loader for the keys we need. Trims leading/trailing
# quotes. No variable expansion — matches our src/config/load.ts behavior.
load_env_var() {
  local key="$1"
  local line value
  line="$(grep -E "^$key=" "$ENV_FILE" | head -1 || true)"
  value="${line#*=}"
  # strip matching surrounding quotes
  if [[ "${value:0:1}" == '"' && "${value: -1}" == '"' ]]; then
    value="${value:1:-1}"
  elif [[ "${value:0:1}" == "'" && "${value: -1}" == "'" ]]; then
    value="${value:1:-1}"
  fi
  printf '%s' "$value"
}

IMAP_HOST="$(load_env_var IMAP_HOST)"
IMAP_PORT="$(load_env_var IMAP_PORT)"
SMTP_HOST="$(load_env_var SMTP_HOST)"
SMTP_PORT="$(load_env_var SMTP_PORT)"
SMTP_USER="$(load_env_var SMTP_USER)"
SMTP_FROM="$(load_env_var SMTP_FROM)"
# SMTP_PASS is deliberately NOT loaded here — it's referenced at runtime
# via `password.cmd = "printenv SMTP_PASS"`, which keeps the secret in
# env only. Config file will be safe to `cat`.

for required in IMAP_HOST IMAP_PORT SMTP_HOST SMTP_PORT SMTP_USER SMTP_FROM; do
  if [[ -z "${!required}" ]]; then
    echo "ERROR: $required is empty in $ENV_FILE — re-run 'skill setup himalaya'." >&2
    exit 4
  fi
done

# Map standard ports to the right encryption type. Hard-coding
# `encryption.type = "tls"` breaks port 587 — that port is submission
# with STARTTLS, not implicit TLS. Picking wrongly yields a cryptic
# "received corrupt message of type InvalidContentType" handshake
# failure, because the client does a TLS handshake against a plaintext
# listener that was expecting EHLO + STARTTLS first.
#
# Rule of thumb:
#   IMAP 993 / SMTP 465 → implicit TLS     ("tls")
#   IMAP 143 / SMTP 587 → STARTTLS         ("start-tls")
#   IMAP 143 / SMTP 25  → plaintext        ("none")
#
# himalaya 1.2 accepts: "tls", "start-tls", "none".
encryption_for_port() {
  case "$1" in
    993|465) echo "tls" ;;
    143|587) echo "start-tls" ;;
    25)      echo "none" ;;
    *)
      # Unknown port — default to TLS and warn. User can edit the
      # generated config by hand if their provider is unusual.
      echo "tls"
      ;;
  esac
}
IMAP_ENC="$(encryption_for_port "$IMAP_PORT")"
SMTP_ENC="$(encryption_for_port "$SMTP_PORT")"
echo "• IMAP  $IMAP_HOST:$IMAP_PORT  → encryption=$IMAP_ENC"
echo "• SMTP  $SMTP_HOST:$SMTP_PORT  → encryption=$SMTP_ENC"

# --- 3. write himalaya config --------------------------------------------
CONFIG_DIR="${HIMALAYA_CONFIG_DIR:-$HOME/.config/himalaya}"
CONFIG_FILE="$CONFIG_DIR/config.toml"
mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_FILE" <<TOML
# Generated by skills/himalaya/install.sh — do not edit by hand.
# Re-run \`andybioticlaw skill setup himalaya\` to refresh values.
#
# Passwords are NOT stored here. They are resolved at runtime from
# environment variables (\`SMTP_PASS\`). The env vars are populated by
# our service's secret-scoping path when it spawns Claude subprocesses
# declaring 'himalaya' as an active skill.

[accounts.personal]
default = true
email = "$SMTP_FROM"

backend.type = "imap"
backend.host = "$IMAP_HOST"
backend.port = $IMAP_PORT
backend.encryption.type = "$IMAP_ENC"
backend.login = "$SMTP_USER"
backend.auth.type = "password"
backend.auth.cmd = "printenv SMTP_PASS"

# Don't try to IMAP-APPEND the sent message to the Sent folder after SMTP
# delivery. Our DB's pending_email_sends + audit tables are the authoritative
# "what did Emma send" record. Asking himalaya to also copy to IMAP just adds
# a second failure mode (e.g. metanet.ch's IMAP APPEND returns an unexpected
# completion tag and himalaya marks the whole send as failed — even though
# the SMTP half already succeeded and the recipient got the mail).
message.send.save-copy = false

message.send.backend.type = "smtp"
message.send.backend.host = "$SMTP_HOST"
message.send.backend.port = $SMTP_PORT
message.send.backend.encryption.type = "$SMTP_ENC"
message.send.backend.login = "$SMTP_USER"
message.send.backend.auth.type = "password"
message.send.backend.auth.cmd = "printenv SMTP_PASS"
TOML

chmod 0644 "$CONFIG_FILE"
echo "✓ wrote $CONFIG_FILE"

# --- 4. smoke test -------------------------------------------------------
# Only runs if SMTP_PASS is also exported — otherwise we skip and rely on
# the next actual session (where our scoped-secret injector will supply
# it) to be the first real test.
if [[ -n "${SMTP_PASS:-}" ]]; then
  echo "Running smoke test (himalaya envelope list -a personal -p 1 -s 1)…"
  if himalaya envelope list -a personal -p 1 -s 1 --output json >/dev/null 2>/tmp/himalaya-smoke.err; then
    echo "✓ himalaya can reach $IMAP_HOST:$IMAP_PORT as $SMTP_USER"
  else
    echo "⚠️  smoke test failed — see /tmp/himalaya-smoke.err"
    cat /tmp/himalaya-smoke.err >&2
    exit 5
  fi
else
  echo "(smoke test skipped — SMTP_PASS not exported in this shell;"
  echo " credentials will be injected when Emma spawns the subprocess.)"
fi

# --- 5. install HITL send wrappers --------------------------------------
# These shell scripts sit between Emma and `himalaya message send`. They
# enforce a database-level invariant that drafting + sending an email
# must span at least two sessions (i.e. a principal user-message in
# between). See skills/himalaya/bin/*.sh for details.
BIN_SRC="$SCRIPT_DIR/bin"
USER_BIN="$HOME/.local/bin"
mkdir -p "$USER_BIN"
ln -sf "$BIN_SRC/himalaya-propose-send" "$USER_BIN/himalaya-propose-send"
ln -sf "$BIN_SRC/himalaya-commit-send"  "$USER_BIN/himalaya-commit-send"
chmod +x "$BIN_SRC/himalaya-propose-send" "$BIN_SRC/himalaya-commit-send"
echo "✓ HITL send wrappers symlinked into $USER_BIN/"
case ":$PATH:" in
  *":$USER_BIN:"*) ;;
  *)
    echo "  NOTE: $USER_BIN is not on PATH in this shell. Emma runs with a clean"
    echo "  env that will find the wrappers via \$SKILL_HIMALAYA_DIR/bin/ — this"
    echo "  only matters for manual shell invocations."
    ;;
esac

echo
echo "himalaya skill installed."
